### ISSUE TITLE
good first issue

### ISSUE THREAD

**Issue by mekaustubh28** [mekaustubh28/Edification#1]
I can't calculate proper score. 
Answer for numerical type is not accepted.

**Comment by Kate028** [comment]
can you elaborate the issue and file name
I want to work on that

**Comment by mekaustubh28** [comment]
yeah acutally I am trying to calculate score including negative marks but........I am getting error in my java script file which I cant resolve.

**Comment by mekaustubh28** [comment]
I am able to fetch correct answers from answer.js
but not able to maniupulate in index.js/javascript

**Comment by mekaustubh28** [comment]
and thanks for considering my project worthy effort to be contributed

**Comment by mihiryadav8264** [comment]
@mekaustubh28  Atlest try to explain the issue properly .
Because  whatever the label you have made no one able to understand..
